export const theme = {
  colors: {
    white: "#FFFFFF",
    lodge: "#7289DA",
    online: "#43B581",
    danger: "#F04747",
    idle: "#fAA61A",
    nitro: "#FF73FA",
    bravery: "#9B84EE",
    balance: "#44DDBF",
    brilliance: "#44DDBF",
    high: "#F57B68",
    skin: "#F9C9A9",
    normal: "#dcddde",
    grey: "#99AAB5",
    lighter: "#626772",
    chatbox: "#40444b",
    chat: "#36393F",
    channels: "#2F3136",
    servers: "#202225",
    black: "#16181a",
  },
  size: {
    mobileS: "320px",
    mobileM: "375px",
    mobileL: "425px",
    tablet: "768px",
    laptop: "1024px",
    laptopL: "1440px",
    desktopS: "1600px",
    desktop: "1920px",
    desktopL: "2560px",
  },
};

export const device = {
  mobileS: `(min-width: ${theme.size.mobileS})`,
  mobileM: `(min-width: ${theme.size.mobileM})`,
  mobileL: `(min-width: ${theme.size.mobileL})`,
  tablet: `(min-width: ${theme.size.tablet})`,
  laptop: `(min-width: ${theme.size.laptop})`,
  laptopL: `(min-width: ${theme.size.laptopL})`,
  desktopS: `(min-width: ${theme.size.desktopS})`,
  desktop: `(min-width: ${theme.size.desktop})`,
  desktopL: `(min-width: ${theme.size.desktopL})`,
};
